### ISSUE TITLE
make website mobile-friendly

### ISSUE THREAD

**Issue by bobheadxi** [ubclaunchpad/ubclaunchpad.com#2]
Need to make a pass over everything when done to make sure nothing looks awful on mobile, and make any minor tweaks as necessary

very useful: https://bulma.io/documentation/modifiers/responsive-helpers/

this is a tracking issue for all the problems the website currently has on mobile

### Known issues

* [x] ~landing area/`Feature` looks strange~ #53 
<img width="352" alt="image" src="https://user-images.githubusercontent.com/23356519/79893318-c3c65e80-83b8-11ea-896b-7024885bb308.png">

* [x] ~`Highlights` reflows incorrectly - I used two sets of columns to get the title aligned, but we may need a better method of doing that which doesn't mess up on mobile (or an alternative rendering)~ #84 
<img width="368" alt="image" src="https://user-images.githubusercontent.com/23356519/79893397-de003c80-83b8-11ea-8656-a2c2b9f7d943.png">

* [x] ~`TeamProjectCard` needs margins on mobile~ #69 
<img width="397" alt="image" src="https://user-images.githubusercontent.com/23356519/79893438-eeb0b280-83b8-11ea-9335-5ab8669e726b.png">

* [x] ~`Join` column fixed and too wide~ #48 
<img width="386" alt="image" src="https://user-images.githubusercontent.com/23356519/79893486-04be7300-83b9-11ea-8711-6fa3d6eca710.png">

* [x] ~`Join` should flow with descriptions -> links instead of the other way around (see above)~ #51 

* [x] ~`Footer` is wild~ #85
<img width="359" alt="image" src="https://user-images.githubusercontent.com/23356519/79893529-1142cb80-83b9-11ea-9daa-7574065c80e3.png">

* [x] ~`tiles` reflows poorly on medium-sized screens (both `Projects` and `Teams`) and overflows off the screen~ #69 
<img width="898" alt="image" src="https://user-images.githubusercontent.com/23356519/79895599-ffaef300-83bb-11ea-8b24-94a7b98a15f9.png">

* [x] ~`Teams` scales poorly on medium-sized screens~ #52 
<img width="949" alt="image" src="https://user-images.githubusercontent.com/23356519/79895531-df7f3400-83bb-11ea-9b47-56f83fcfb0d1.png">

**Comment by bobheadxi** [comment]
Let's open up individual issues as they come up
